identifiers:
    issuer: "https://example.com/issuer"
    verifier: "https://example.com/verifier"

key_settings:
    key_size: 256

    kty: EC

    issuer_key:
        kty: EC
        d: Ur2bNKuBPOrAaxsRnbSH6hIhmNTxSGXshDSUD1a1y7g
        crv: P-256
        x: b28d4MwZMjw8-00CG4xfnn9SLMVMM19SlqZpVb_uNtQ
        y: Xv5zWwuoaTgdS6hV43yI6gBwTnjukmFQQnJ_kCxzqk8

    holder_key:
        kty: EC
        d: 5K5SCos8zf9zRemGGUl6yfok-_NiiryNZsvANWMhF-I
        crv: P-256
        x: TCAER19Zvu3OHF4j4W4vfSVoHIP1ILilDls7vCeGemc
        y: ZxjiWWbZMQGHVWKVQ4hbSIirsVfuecCE6t4jT9F2HZQ

key_binding_nonce: "1234567890"
